### ISSUE TITLE
ActiveRecord 6.0 dependency

### ISSUE THREAD

**Issue by robinboening** [mrrooijen/graphql_activerecord_autoselect#1]
Hey there! 👋 

Thanks for the gem, I am just trying it out as I was looking for a tool supporting my graphql setup in selecting the right columns with AR.

My app is still running on Rails 5.2 and updating is not an option in the next weeks/couple of months, so I am wondering if this gem has really a hard dependency on v6 as defined in the gemspec? I am happy to try with Rails 5 in case you've just never tried it.

❤️ for open sourcing your work!

**Comment by mrrooijen** [comment]
Hey Robin,

ActiveRecord 5 should be compatible, but I'll have to see about Ruby 2.7, which is what we're currently targeting. I'll run a few tests later today to see whether or not we can relax the dependency on ActiveRecord 6 to include at least 5.

**Comment by robinboening** [comment]
Thanks for the lightning fast response ⚡ 👍 

I forked the gem and relaxed the dependency to AR v5.2. No immediate error. I wasn't able to get it working though, but I think that is just me not using it right. Looking at the code (I was very happy its so lightweight 👍) I also thought it should work with lower AR versions as its just extending AR and not having any dependency other than `select` which exists since v3.

**Comment by robinboening** [comment]
I am currently using Ruby 2.6.5 and haven't gotten any immediate error. I also haven't immediately seen anything in the code that creates a requirement for ruby greater than 2.1 (2.1 as you're using required keyword arguments)

But since graphql has ruby >= 2.2 defined this is probably the lowest possible version in here as well.

**Comment by robinboening** [comment]
I can confirm it's working with Ruby 2.6.5 and active record 5.2

**Comment by mrrooijen** [comment]
It looks like it's working with ActiveRecord 5, so we'll add support for that. If anyone else needs pre-5 support further down the line we can always look into it. For now we'll leave it at AR 5+.

The tests pass against Ruby 2.5, 2.6, 2.7 with ActiveRecord 5 and 6.

https://github.com/mrrooijen/graphql_activerecord_autoselect/actions/runs/158423735

Can you try adding the activerecord-5 branch to your application to see if it works?

```ruby
gem "graphql_activerecord_autoselect",
  :github => "mrrooijen/graphql_activerecord_autoselect",
  :branch => "activerecord-5"
```

If there aren't any issues I'll go ahead and push out a new gem.

**Comment by robinboening** [comment]
Looks good to me! I used your branch and its working as well. 🎉

**Comment by mrrooijen** [comment]
Just pushed v1.0.1 so you can now upgrade to that. 👍
