### ISSUE TITLE
Example for `autoselect` on an ActiveRecord::Base instance

### ISSUE THREAD

**Issue by robinboening** [mrrooijen/graphql_activerecord_autoselect#2]
The README shows two examples, both of them presenting the use case of `autoselect` in the context of an ActiveRecord relation.

> The autoselect method is made available to all **instances of ActiveRecord::Base** and ActiveRecord::Relations in classes where the GraphQLActiveRecordAutoSelect refinement is used (using GraphQLActiveRecordAutoSelect).

I am trying to apply `autoselect` on a single record (`ActiveRecord::Base` instance). I can see the highlighted part of the quoted paragraph above is reflected in the code: https://github.com/mrrooijen/graphql_activerecord_autoselect/blob/master/lib/graphql_activerecord_autoselect.rb#L9 but I don't get it working.

This is what I did:

It feels wrong to create a resolver method for every single field, but I tried this as I found it might be a quick way to test it:

```
module Types
  class AdventureType < Types::BaseObject
    using GraphQLActiveRecordAutoSelect

    field :id, ID, "The unique ID", null: false, extras: [:lookahead]

    def id(lookahead:)
      object.autoselect(lookahead)
    end
  end
end
```

This results in the following error

```
undefined method `autoselect' for #<Adventure:0x0000558c964a3850>
```

What would be the right way to use it? Could you provide an example for using `autoselect` on an instance of `ActiveRecord::Base`, please? 

Thank you so much!

**Comment by robinboening** [comment]
Sorry, I got it now and it makes sense ;)

In `QueryType` I have the root queries and the resolvers defined. I just had to add `autoselect` in there.

```
module Types
  class QueryType < Types::BaseObject
    using GraphQLActiveRecordAutoSelect

    field :adventures,
    [Types::AdventureType],
    null: true,
    extras: [:lookahead],
    description: "Returns adventures" do
      argument ids, ...
    end

    def adventures(lookahead:, ids: nil, ...)
      adventures = Adventure.unscoped
      ...
      adventures.autoselect(lookahead)
    end
  end
end
```

**Comment by mrrooijen** [comment]
I made a mistake in stating that it's added to all instances.

It's added to all instances of `ActiveRecord::Relations`, but for `ActiveRecord::Base` it's actually only provided at the class level. So you can only call it on relations of an object (e.g. `object.adventures.autoselect(lookahead)`) or on the class itself (e.g. `Adventure.autoselect(lookahead)`).
